{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ if .Values.rbac.clusterWideAccess }}"ClusterRole"{{ else }}"Role"{{ end }}
metadata:
  name: {{ include "gitlab-runner.fullname" . }}
  labels:
    app: {{ include "gitlab-runner.fullname" . }}
    chart: {{ include "gitlab-runner.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
rules:
{{- if .Values.rbac.podSecurityPolicy.enabled }}
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
{{ toYaml .Values.rbac.podSecurityPolicy.resourceNames | indent 2 }}
{{- end }}
- apiGroups: [""]
  {{- if .Values.rbac.resources }}
  resources: [{{ join ", " .Values.rbac.resources }}]
  {{- else }}
  resources: ["*"]
  {{- end }}
  {{- if .Values.rbac.verbs }}
  verbs: [{{ join ", " .Values.rbac.verbs }}]
  {{- else }}
  verbs: ["*"]
  {{- end }}
{{- end -}}
